version: '3.8'
services:
  icdify.api:
    container_name: icdify.api
    build:
      context: ..
      dockerfile: ICDify.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
